name: cubicode
version: 1.0.0+1
publish_to: none
description: COMP3330 Project Cubicode
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  audioplayers: ^6.5.1
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.1.0
  blocky:
    path: packages/blocky
  cache:
    path: packages/cache
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  font_awesome_flutter: ^10.6.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.1
  freezed_annotation: ^3.1.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  topics_repository:
    path: packages/topics_repository
  transparent_image:
    path: packages/transparent_image
  projects_repository:
    path: packages/projects_repository
  quizzes_repository:
    path: packages/quizzes_repository
  uuid: ^4.2.1
  xterm: ^4.0.0
  geolocator: ^14.0.2
  async: ^2.11.0
  crypto: ^3.0.3
  rxdart: ^0.28.0
dev_dependencies:
  analysis_options:
    path: packages/analysis_options
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/soundpack/
    - assets/covers/
    - assets/guide/hello-world/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
flutter_native_splash:
  color: "#1C1B1F"
  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#4ffdff"
  image: assets/icon/icon.png
